services:
  apache:
    depends_on:
      - mysql
    ports:
      - "8080:80"
    image: php:8.2-apache
    volumes:
      - ./src:/var/www/html
    restart: always
    command: 
      "bash -c 'docker-php-ext-install mysqli pdo pdo_mysql && apache2-foreground'"
    environment:
      MYSQL_HOST: mysql

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command: --init-file /var/lib/sql_init/init.sql
    volumes:
      - ./sql:/var/lib/sql_init/
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: