services:
  php-apache:
    build: .
    container_name: apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command: --init-file /var/lib/sql_init/init.sql
    volumes:
      - ./sql:/var/lib/sql_init/
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: